apiVersion: v1
kind: Service
metadata:
  name: homemind-api
  namespace: homemind-prod
  labels:
    app.kubernetes.io/name: homemind-api
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 5001
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: homemind-api
